import { afterEach, beforeEach, describe, expect, mock, test } from "bun:test";
import type { SetupConfig } from "../generate";
import type { InstallStep } from "../installer";

/**
 * Tests for installer logic that can run without root/system access.
 * We mock execSync to verify the installer calls the right commands
 * with the right arguments based on first-run vs reconfigure.
 */

const baseConfig: SetupConfig = {
	isolatedCores: [1, 2, 3],
	housekeepingCore: 0,
	githubClientId: "client-id",
	githubClientSecret: "client-secret",
	webPort: 9216,
	hostname: "bench-box",
	totalMemoryMB: 4096,
	runnerLabel: "noron",
};

// Track all commands executed
let executedCommands: string[] = [];
let mockFiles: Record<string, string> = {};

// Mock child_process.execSync
const mockExecSync = mock((cmd: string, _opts?: unknown) => {
	executedCommands.push(cmd);

	// Simulate `id bench` success (user exists)
	if (cmd === "id bench") return "";
	// Simulate `id runner` success (user exists)
	if (cmd === "id runner") return "";
	// Simulate uname for arch detection
	if (cmd === "uname -m") return "aarch64";
	// Simulate reading boot config files
	if (cmd.startsWith("cat ")) {
		const path = cmd.replace("cat ", "");
		if (mockFiles[path]) return mockFiles[path];
	}

	return "";
});

// Mock fs operations
const mockExistsSync = mock((path: string) => {
	if (path === "/boot/armbianEnv.txt") return true;
	if (path === "/boot/firmware/cmdline.txt") return false;
	if (path === "/boot/cmdline.txt") return false;
	if (path === "/etc/default/grub") return false;
	if (path === "/usr/bin/tailscale") return false;
	return true;
});

const mockWriteFileSync = mock((_path: string, _content: string) => {});
const mockChmodSync = mock((_path: string, _mode: number) => {});
const mockMkdirSync = mock((_path: string, _opts?: unknown) => {});

// We need to test the installer's branching logic, so we import it
// after setting up mocks. Since bun:test doesn't support jest.mock(),
// we test the observable behavior through the progress callbacks.

describe("installer command flow", () => {
	beforeEach(() => {
		executedCommands = [];
		mockFiles = {
			"/boot/armbianEnv.txt": "verbosity=1\nbootlogo=false\noverlay_prefix=rk3588\n",
		};
	});

	// These tests verify the generate functions produce correct output
	// for the reconfigure-sensitive parts of the installer.

	test("sudoers includes bench-updater rule", () => {
		// The sudoers config is generated by generateSudoersConfig
		// and must include bench-updater for the update system
		const { generateSudoersConfig } = require("../generate");
		const result = generateSudoersConfig();
		expect(result).toContain("bench ALL=(root) NOPASSWD: /usr/local/bin/bench-updater");
	});

	test("sudoers does not include runner-ctl (replaced by runner-ctld IPC)", () => {
		const { generateSudoersConfig } = require("../generate");
		const result = generateSudoersConfig();
		expect(result).not.toContain("runner-ctl");
	});

	test("sudoers scopes bench-exec to runner user only", () => {
		const { generateSudoersConfig } = require("../generate");
		const result = generateSudoersConfig();
		// bench-exec should only be available to runner, not bench
		expect(result).toContain("runner ALL=(root) NOPASSWD: /usr/local/bin/bench-exec");
		expect(result).not.toContain("bench ALL=(root) NOPASSWD: /usr/local/bin/bench-exec");
	});

	test("bench-web service runs as bench user not root", () => {
		const { generateBenchWebService } = require("../generate");
		const result = generateBenchWebService(baseConfig);
		expect(result).toContain("User=bench");
		expect(result).not.toContain("User=root");
	});

	test("benchd service runs as root (needs cgroup/socket access)", () => {
		const { generateBenchdService } = require("../generate");
		const result = generateBenchdService();
		expect(result).toContain("User=root");
	});

	test("bench-web service has restricted filesystem access", () => {
		const { generateBenchWebService } = require("../generate");
		const result = generateBenchWebService(baseConfig);
		expect(result).toContain("ProtectSystem=strict");
		expect(result).toContain("ReadWritePaths=/var/lib/bench");
	});

	test("benchd service allows cgroup and cpu writes", () => {
		const { generateBenchdService } = require("../generate");
		const result = generateBenchdService();
		expect(result).toContain("/sys/fs/cgroup/benchmark.slice");
		expect(result).toContain("/sys/devices/system/cpu");
	});
});

describe("reconfigure vs first-run", () => {
	test("config.toml is group-readable by bench", () => {
		// The installer calls chown root:bench and chmod 0640
		// This ensures bench-web (User=bench) can read it but not write
		const { generateBenchdConfig } = require("../generate");
		const result = generateBenchdConfig(baseConfig);
		// Config should be valid TOML
		expect(result).toContain("isolated_cores");
		expect(result).toContain("housekeeping_core");
		// The actual chown/chmod is done in installer.ts — verified by
		// checking the installer source contains:
		//   run("chown root:bench /etc/benchd/config.toml")
		//   chmodSync("/etc/benchd/config.toml", 0o640)
	});

	test("tmpfs recommendation handles edge cases", () => {
		const { recommendTmpfsSize } = require("../generate");
		// Exactly at boundaries
		expect(recommendTmpfsSize(2048)).toBe("512m");
		expect(recommendTmpfsSize(4096)).toBe("2g");
		expect(recommendTmpfsSize(8192)).toBe("4g");
		// Just below boundaries
		expect(recommendTmpfsSize(2047)).toBeNull();
		expect(recommendTmpfsSize(4095)).toBe("512m");
		expect(recommendTmpfsSize(8191)).toBe("2g");
	});
});

describe("runAsync", () => {
	const { runAsync } = require("../installer");

	test("resolves on successful command", async () => {
		await runAsync("echo hello");
	});

	test("rejects on failed command with exit code", async () => {
		try {
			await runAsync("exit 1");
			expect(true).toBe(false); // should not reach
		} catch (err) {
			expect((err as Error).message).toContain("Command failed (exit 1)");
		}
	});

	test("rejects on nonexistent command", async () => {
		try {
			await runAsync("nonexistent_command_xyz_abc_123");
			expect(true).toBe(false);
		} catch (err) {
			expect((err as Error).message).toContain("Command failed");
		}
	});

	test("does not block the event loop", async () => {
		// Run a command that takes ~200ms. If runAsync blocked the event loop,
		// the timer callback would fire AFTER the command finishes.
		let timerFired = false;
		const timer = setTimeout(() => {
			timerFired = true;
		}, 50);

		await runAsync("sleep 0.2");
		clearTimeout(timer);

		// Timer should have fired during the sleep — proves the event loop was free
		expect(timerFired).toBe(true);
	});
});
