import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

/** Runtime configuration for benchd, persisted as TOML */
export interface BenchdConfig {
	isolatedCores: number[];
	housekeepingCore: number;
	targetTempC: number;
	thermalHistorySize: number;
	thermalPollIntervalMs: number;
	thermalTimeoutMs: number;
	thermalMarginC: number;
	thermalBaselineSettlingS: number;
	socketPath: string;
	benchmarkSlice: string;
	benchmarkCgroup: string;
	benchTmpfs: string;
	lockDisconnectGraceMs: number;
	tokenExpiryHours: number;
	jobTimeoutMs: number;
	updateRepo: string;
	updateAuto: boolean;
	updateCheckIntervalHours: number;
	runnerLabel: string;
}

/** Default path for the config file */
export const CONFIG_PATH = "/etc/benchd/config.toml";

/** Default configuration values (matches original hardcoded constants) */
export const DEFAULT_CONFIG: BenchdConfig = {
	isolatedCores: [1, 2, 3],
	housekeepingCore: 0,
	targetTempC: 45,
	thermalHistorySize: 300,
	thermalPollIntervalMs: 1000,
	thermalTimeoutMs: 300_000,
	thermalMarginC: 3,
	thermalBaselineSettlingS: 30,
	socketPath: "/var/run/benchd.sock",
	benchmarkSlice: "benchmark.slice",
	benchmarkCgroup: "/sys/fs/cgroup/benchmark.slice",
	benchTmpfs: "/mnt/bench-tmpfs",
	lockDisconnectGraceMs: 5000,
	tokenExpiryHours: 24,
	jobTimeoutMs: 600_000,
	updateRepo: "",
	updateAuto: true,
	updateCheckIntervalHours: 1,
	runnerLabel: "noron",
};

/**
 * Parse a simple TOML config file into a partial BenchdConfig.
 * Supports: strings, integers, floats, booleans, and integer arrays.
 * This is intentionally minimal — the config format is flat.
 */
export function parseToml(content: string): Record<string, unknown> {
	const result: Record<string, unknown> = {};

	for (const rawLine of content.split("\n")) {
		const line = rawLine.trim();
		if (!line || line.startsWith("#")) continue;

		const eqIdx = line.indexOf("=");
		if (eqIdx === -1) continue;

		const key = line.slice(0, eqIdx).trim();
		const rawValue = line.slice(eqIdx + 1).trim();

		result[key] = parseTomlValue(rawValue);
	}

	return result;
}

function parseTomlValue(raw: string): unknown {
	// Array: [1, 2, 3]
	if (raw.startsWith("[") && raw.endsWith("]")) {
		const inner = raw.slice(1, -1).trim();
		if (!inner) return [];
		return inner.split(",").map((s) => parseTomlValue(s.trim()));
	}
	// String: "value"
	if (raw.startsWith('"') && raw.endsWith('"')) {
		return raw.slice(1, -1);
	}
	// Boolean
	if (raw === "true") return true;
	if (raw === "false") return false;
	// Number
	const num = Number(raw);
	if (!Number.isNaN(num)) return num;
	// Bare string fallback
	return raw;
}

/** Serialize a BenchdConfig to TOML format */
export function serializeToml(config: BenchdConfig): string {
	const lines: string[] = [
		"# benchd configuration",
		"# Generated by benchd — edit as needed, restart benchd to apply changes",
		"",
		"# CPU core allocation",
		`isolated_cores = [${config.isolatedCores.join(", ")}]`,
		`housekeeping_core = ${config.housekeepingCore}`,
		"",
		"# Thermal settings",
		`target_temp_c = ${config.targetTempC}`,
		`thermal_history_size = ${config.thermalHistorySize}`,
		`thermal_poll_interval_ms = ${config.thermalPollIntervalMs}`,
		`thermal_timeout_ms = ${config.thermalTimeoutMs}`,
		`thermal_margin_c = ${config.thermalMarginC}`,
		`thermal_baseline_settling_s = ${config.thermalBaselineSettlingS}`,
		"",
		"# Paths",
		`socket_path = "${config.socketPath}"`,
		`benchmark_slice = "${config.benchmarkSlice}"`,
		`benchmark_cgroup = "${config.benchmarkCgroup}"`,
		`bench_tmpfs = "${config.benchTmpfs}"`,
		"",
		"# Lock behavior",
		`lock_disconnect_grace_ms = ${config.lockDisconnectGraceMs}`,
		"",
		"# Token expiry",
		`token_expiry_hours = ${config.tokenExpiryHours}`,
		"",
		"# Job limits",
		`job_timeout_ms = ${config.jobTimeoutMs}`,
		"",
		"# Self-update settings",
		`update_repo = "${config.updateRepo}"`,
		`update_auto = ${config.updateAuto}`,
		`update_check_interval_hours = ${config.updateCheckIntervalHours}`,
		"",
		"# Runner label",
		`runner_label = "${config.runnerLabel}"`,
		"",
	];
	return lines.join("\n");
}

/** Map TOML snake_case keys to camelCase config keys */
const KEY_MAP: Record<string, keyof BenchdConfig> = {
	isolated_cores: "isolatedCores",
	housekeeping_core: "housekeepingCore",
	target_temp_c: "targetTempC",
	thermal_history_size: "thermalHistorySize",
	thermal_poll_interval_ms: "thermalPollIntervalMs",
	thermal_timeout_ms: "thermalTimeoutMs",
	thermal_margin_c: "thermalMarginC",
	thermal_baseline_settling_s: "thermalBaselineSettlingS",
	socket_path: "socketPath",
	benchmark_slice: "benchmarkSlice",
	benchmark_cgroup: "benchmarkCgroup",
	bench_tmpfs: "benchTmpfs",
	lock_disconnect_grace_ms: "lockDisconnectGraceMs",
	token_expiry_hours: "tokenExpiryHours",
	job_timeout_ms: "jobTimeoutMs",
	update_repo: "updateRepo",
	update_auto: "updateAuto",
	update_check_interval_hours: "updateCheckIntervalHours",
	runner_label: "runnerLabel",
};

/**
 * Load a BenchdConfig from a TOML file.
 * Returns null if the file does not exist.
 * Missing keys are filled from DEFAULT_CONFIG.
 */
export function loadConfig(path: string = CONFIG_PATH): BenchdConfig | null {
	if (!existsSync(path)) return null;

	try {
		const content = readFileSync(path, "utf-8");
		const parsed = parseToml(content);
		const config = { ...DEFAULT_CONFIG };

		for (const [tomlKey, value] of Object.entries(parsed)) {
			const configKey = KEY_MAP[tomlKey];
			if (configKey) {
				(config as Record<string, unknown>)[configKey] = value;
			}
		}

		return config;
	} catch {
		return null;
	}
}

/**
 * Write a BenchdConfig to a TOML file.
 * Creates parent directories if they don't exist.
 */
export function writeDefaultConfig(
	path: string,
	config: BenchdConfig,
): void {
	const dir = dirname(path);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}
	writeFileSync(path, serializeToml(config), "utf-8");
}
